/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as ExtensionRouteImport } from './routes/extension'
import { Route as IntelligenceRouteImport } from './routes/intelligence'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as ReportRouteImport } from './routes/report'
import { Route as ReportSubmittedRouteImport } from './routes/report-submitted'
import { Route as ResultRouteImport } from './routes/result'
import { Route as ScreenshotRouteImport } from './routes/screenshot'
import { Route as TrackRouteImport } from './routes/track'
import { Route as UrlRouteImport } from './routes/url'
import { Route as AlertsIdRouteImport } from './routes/alerts.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionRoute = ExtensionRouteImport.update({
  id: '/extension',
  path: '/extension',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceRoute = IntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportSubmittedRoute = ReportSubmittedRouteImport.update({
  id: '/report-submitted',
  path: '/report-submitted',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenshotRoute = ScreenshotRouteImport.update({
  id: '/screenshot',
  path: '/screenshot',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const UrlRoute = UrlRouteImport.update({
  id: '/url',
  path: '/url',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsIdRoute = AlertsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AlertsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRouteWithChildren
  '/extension': typeof ExtensionRoute
  '/intelligence': typeof IntelligenceRoute
  '/portal': typeof PortalRoute
  '/report': typeof ReportRoute
  '/report-submitted': typeof ReportSubmittedRoute
  '/result': typeof ResultRoute
  '/screenshot': typeof ScreenshotRoute
  '/track': typeof TrackRoute
  '/url': typeof UrlRoute
  '/alerts/$id': typeof AlertsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRouteWithChildren
  '/extension': typeof ExtensionRoute
  '/intelligence': typeof IntelligenceRoute
  '/portal': typeof PortalRoute
  '/report': typeof ReportRoute
  '/report-submitted': typeof ReportSubmittedRoute
  '/result': typeof ResultRoute
  '/screenshot': typeof ScreenshotRoute
  '/track': typeof TrackRoute
  '/url': typeof UrlRoute
  '/alerts/$id': typeof AlertsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRouteWithChildren
  '/extension': typeof ExtensionRoute
  '/intelligence': typeof IntelligenceRoute
  '/portal': typeof PortalRoute
  '/report': typeof ReportRoute
  '/report-submitted': typeof ReportSubmittedRoute
  '/result': typeof ResultRoute
  '/screenshot': typeof ScreenshotRoute
  '/track': typeof TrackRoute
  '/url': typeof UrlRoute
  '/alerts/$id': typeof AlertsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/extension'
    | '/intelligence'
    | '/portal'
    | '/report'
    | '/report-submitted'
    | '/result'
    | '/screenshot'
    | '/track'
    | '/url'
    | '/alerts/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/extension'
    | '/intelligence'
    | '/portal'
    | '/report'
    | '/report-submitted'
    | '/result'
    | '/screenshot'
    | '/track'
    | '/url'
    | '/alerts/$id'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/extension'
    | '/intelligence'
    | '/portal'
    | '/report'
    | '/report-submitted'
    | '/result'
    | '/screenshot'
    | '/track'
    | '/url'
    | '/alerts/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRouteWithChildren
  ExtensionRoute: typeof ExtensionRoute
  IntelligenceRoute: typeof IntelligenceRoute
  PortalRoute: typeof PortalRoute
  ReportRoute: typeof ReportRoute
  ReportSubmittedRoute: typeof ReportSubmittedRoute
  ResultRoute: typeof ResultRoute
  ScreenshotRoute: typeof ScreenshotRoute
  TrackRoute: typeof TrackRoute
  UrlRoute: typeof UrlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extension': {
      id: '/extension'
      path: '/extension'
      fullPath: '/extension'
      preLoaderRoute: typeof ExtensionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence': {
      id: '/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof IntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-submitted': {
      id: '/report-submitted'
      path: '/report-submitted'
      fullPath: '/report-submitted'
      preLoaderRoute: typeof ReportSubmittedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screenshot': {
      id: '/screenshot'
      path: '/screenshot'
      fullPath: '/screenshot'
      preLoaderRoute: typeof ScreenshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/url': {
      id: '/url'
      path: '/url'
      fullPath: '/url'
      preLoaderRoute: typeof UrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts/$id': {
      id: '/alerts/$id'
      path: '/$id'
      fullPath: '/alerts/$id'
      preLoaderRoute: typeof AlertsIdRouteImport
      parentRoute: typeof AlertsRoute
    }
  }
}

interface AlertsRouteChildren {
  AlertsIdRoute: typeof AlertsIdRoute
}

const AlertsRouteChildren: AlertsRouteChildren = {
  AlertsIdRoute: AlertsIdRoute,
}

const AlertsRouteWithChildren =
  AlertsRoute._addFileChildren(AlertsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRouteWithChildren,
  ExtensionRoute: ExtensionRoute,
  IntelligenceRoute: IntelligenceRoute,
  PortalRoute: PortalRoute,
  ReportRoute: ReportRoute,
  ReportSubmittedRoute: ReportSubmittedRoute,
  ResultRoute: ResultRoute,
  ScreenshotRoute: ScreenshotRoute,
  TrackRoute: TrackRoute,
  UrlRoute: UrlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
